### ISSUE TITLE
toast component

### ISSUE THREAD

**Issue by killerdaisies** [Aid-Pioneers/shipment-aid-tracker#34]
- gets triggered and you can pass in information on whether something was successful or failed. 

<img width="645" alt="Screenshot 2023-10-20 at 15 24 50" src="https://github.com/Aid-Pioneers/shipment-aid-tracker/assets/10759646/151af196-5ec7-4007-be01-2df487ea4e7d">

**Comment by JonNorman** [comment]
Have started using this in #45
