### ISSUE TITLE
Sign in page redirect to root which is still sign in  

### ISSUE THREAD

**Issue by killerdaisies** [Aid-Pioneers/shipment-aid-tracker#62]

**Comment by JonNorman** [comment]
It currently navigates to the [shipments](https://github.com/Aid-Pioneers/shipment-aid-tracker/blob/main/src/containers/sign-in/index.tsx#L27) page. At some point we'll want it to navigate to the `projects` page, but that can be tracked as part of that work (i.e. when we've built the projects page).
